# Generated by Django 3.2.5 on 2021-07-10 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolboxapp', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='deadline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
