# Generated by Django 3.2.5 on 2021-07-10 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolboxapp', '0003_alter_food_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
