# Generated by Django 3.2.5 on 2021-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolboxapp', '0004_auto_20210710_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
