# Generated by Django 3.2.5 on 2021-07-17 12:34

import coolboxapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolboxapp', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', coolboxapp.models.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='owner',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='username'),
        ),
    ]
