# Generated by Django 3.2.5 on 2021-07-17 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolboxapp', '0007_auto_20210717_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
